#' @title Number of group
#' @description Provides the number of group in a group matrix.
#' @param group \code{matrix} of \code{integer} indicating the group elements belong (rows) for various partition (columns), as generated by the function \code{group_matrix}.
#' @export
#' @examples
#' group <- t(gtools::permutations(3,3,1:3))
#' group_nb(group)
group_nb <- function(group){
  group_values <- unique(as.numeric(group))
  n_group <- length(group_values)
  return(n_group)
}
