#' @title Group matrix
#' @description Generate a matrix of group, from a division matrix.
#' @param division \code{matrix} of position that define a new group (rows) for different partitions (columns), as generated by the function \code{group_division}.
#' @param n_row \code{integer}, the number of row of the matrix to build, which should equal the length of the vector to be classified.
#' @return Return a \code{matrix} of \code{integer} representing the group to which elements of a vector might belong.
#' @details Division is checked for validity before generating matrix.
#' @export
#' @examples
#' #General example
#' x <- sample(1:100, 10)
#' division <- group_division(x, n_group = 2, min_group = 2)
#' group_matrix(n_row = length(x), division)
#'
group_matrix <- function(n_row, division){
  #Convert division (matrix of position that define a new group) into a matrix of the corresponding groups
  M <- matrix(NA, ncol = ncol(division), nrow = n_row)
  for(i in seq_len(ncol(division))){
    M[,i] <- group_vector(n_row, division[,i])
  }
  return(M)
}
