#' @title Critical values
#' @description Generate critical values associated with divisions.
#' @param x \code{numeric}, an ordered vector of elements.
#' @param division \code{matrix} of position that define a new group (rows) for different partitions (columns), as generated by the function \code{group_division}.
#' @return Return a \code{matrix} of the same dimension as \code{division}, containing the average values of \code{x} for the position defined in the \code{division} and the position preceeding it.
#' @import dplyr
#' @export
#' @examples
#' #General example
#' x <- sample(1:100, 10)
#' division <- group_division(x, n_group = 3, min_group = 2)
#' group_crit(x, division)
group_crit <- function(x, division){
  #Check division is appropriate
  group_division_check(n_row = length(x), division)

  crit <- list()
  for(i in seq_len(nrow(division))){
    crit[[i]] <- (x[division[i,]] + x[division[i,] - 1])/2
  }
  #crit_df <- as.data.frame(bind_cols(crit))
  crit_matrix <- t(bind_cols(crit))
  rownames(crit_matrix) <- NULL
  return(crit_matrix)
}
