#' @title Quadrat count prediction
#' @description Count the number of points in quadrats on the diagonal specified by \code{trend}, from existing an data count.
#' @param Q \code{data.frame} of quadrat counts, as generated by the function \code{quadrat_count}. Must possesses a squared number of elements.
#' @param trend \code{character}, either \code{positive} or \code{negative}.
#' @return Return a \code{data.frame} with columns named \code{ij}, after the quadrat, with i the quadrat index on the x-axis and j the quadrat index on the y-axis. Each line correspond to a partition of \code{group_y}.
#' @export
#' @examples
#' #Generate data
#' ##Data
#' n = 10
#' x <- rnorm(n)
#' y <- rnorm(n)
#' ##Group x, only one partition
#' division_x  <- group_division(y, 2, min_group = 2)
#' group_x <- group_matrix(n, division_x[,1 , drop = FALSE])
#'
#' ##Group y, multiple partition
#' division  <- group_division(y, 2, min_group = 2)
#' group_y <- group_matrix(n, division)
#'
#' #Compute the number of elements in each quadrat
#' Q <- quadrat_count(group_x, group_y)
#'
#' #Compute the number of element on the positive diagonal
#' quadrat_count_pred(Q = Q, trend = "positive")
#'
quadrat_count_pred <- function(Q, trend){
  #Define name of quadrat where points are expected to be
  n_group <- sqrt(ncol(Q))
  quadrat_pred <- quadrat_name_pred(n_group, trend)
  #Compute the sum of point in selected quadrats
  Q_pred <- apply(Q[,quadrat_pred], MARGIN = 1, sum)
  return(Q_pred)
}


